# Generated by Django 5.0.4 on 2024-05-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SeasoningModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tbsp", models.FloatField(default=0.0)),
                ("tsp", models.FloatField(default=0.0)),
            ],
        ),
    ]
