# Generated by Django 5.0.4 on 2024-05-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calcpost", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seasoningmodel",
            name="hiraname",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="seasoningmodel",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
