# Generated by Django 5.0.4 on 2024-05-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calcpost", "0002_seasoningmodel_hiraname_alter_seasoningmodel_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seasoningmodel",
            options={"ordering": ("name",)},
        ),
        migrations.AlterField(
            model_name="seasoningmodel",
            name="name",
            field=models.CharField(max_length=255, verbose_name="名前"),
        ),
    ]
